---
k3s_version: v1.23.1-rc1+k3s1
ansible_user: mxp
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--write-kubeconfig-mode=644 --disable servicelb --disable traefik"
extra_agent_args: ""
